### ISSUE TITLE
Support Rider for Unreal Engine

### ISSUE THREAD

**Issue by maddouri** [itechbear/CLion-MacroFormatter#5]
CLion-MacroFormatter is an invaluable tool when using CLion for editing macro-heavy code.

Since Unreal-Engine-based code relies often on complex macros and the default macro expansion in Rider is similar to that of CLion (i.e. single-level expansion with no formatting), I think that this plugin will provide great value for the users of this new Jetbrains IDE.

Therefore, could you please make CLion-MacroFormatter available for the "Rider for Unreal Engine" IDE ? (https://www.jetbrains.com/lp/rider-unreal/)

Thank you in advance for considering this request!

ps: I understand that having "CLion" in the "CLion-MacroFormatter" name might seem odd if the plugin is enabled for Rider, but I think that users (such as myself) who get great value from this plugin can easily get over that 😉

**Comment by itechbear** [comment]
Hi maddouri,

Thanks for your interests in this plugin.

While I can promise you nothing, because I'm totally new to both Rider and Unreal Engine, I clicked the "Join the early preview" button and filled my information to see whether I can get an EAP version and how I can help.

I'll post here if I have any update.

**Comment by itechbear** [comment]
I just got an email nofifying me an EAP version is available for me. It's really fast. I'll spend some time during the holiday to see whether it's feasible to "migrate" this plugin to Rider.

**Comment by itechbear** [comment]
Hi maddouri,

It seems Rider is not built upon CLion and they have many differences. While I think a similar plugin is feasible, I don't have any big trunk of time developing it. Sorry about that.

**Comment by maddouri** [comment]
That's unfortunate. Thanks anyway for having checked the feasibility.
